# Generated by Django 4.1.1 on 2022-11-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('is_remote', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=30)),
                ('posted_at', models.DateTimeField()),
                ('contract', models.CharField(max_length=50)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobslist_app.company')),
                ('languages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobslist_app.programminglanguage')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobslist_app.location')),
            ],
        ),
    ]
