# Generated by Django 4.1.1 on 2022-11-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobslist_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='languages',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='languages',
            field=models.ManyToManyField(to='jobslist_app.programminglanguage'),
        ),
    ]
