# Generated by Django 4.1.1 on 2022-11-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobslist_app', '0003_joboffer_tools_alter_location_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
