# Generated by Django 4.1.3 on 2022-11-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobslist_app', '0004_alter_location_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(null=True, upload_to='company-logos'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
