# Generated by Django 4.1.3 on 2022-11-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobslist_app', '0005_company_logo_alter_location_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(null=True, upload_to='company-logos'),
        ),
    ]
