# Generated by Django 4.1.4 on 2022-12-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobslist_app', '0008_rename_contract_contract_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='level',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='name',
        ),
    ]
