# Generated by Django 4.1.4 on 2022-12-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobslist_app', '0009_rename_level_level_name_rename_role_role_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tools',
            new_name='Tool',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
